from __future__ import annotations

from arch_decisions.domain.architecture_decision import (
    ARCHITECTURE_DECISION_STATUS,
    ArchitectureDecision,
)

ARCHITECTURE_DECISION_SEEDS: list[ArchitectureDecision] = [
    ArchitectureDecision(
        id='seed-startup-cost-optimized',
        title='Startup cost-optimized stack',
        status=ARCHITECTURE_DECISION_STATUS,
        summary='Cost-first choices for a 1–5 person team: EC2, Parameter Store, and GitHub Actions under low steady traffic.',
        createdAt='2026-01-10T10:00:00.000Z',
        content='# Architecture Decision Record\n\n## Status\nproposed\n\n## Context\n- Team size: 1-5\n- Traffic pattern: low-steady\n- Budget sensitivity: cost-optimized\n- Compliance requirements: none\n- Operational maturity: minimal\n\n## Decision\n- **Compute:** EC2\n  - Alternatives: ECS, Lambda\n- **Secrets:** AWS Parameter Store\n  - Alternatives: AWS Secrets Manager, Environment Variables\n- **CI/CD:** GitHub Actions\n  - Alternatives: GitLab CI, Jenkins\n\n## Consequences\n- Fast to operate with a small team and a tight budget.\n- Manual EC2 operations are acceptable while maturity is low.\n\n## Alternatives Considered\n- Compute alternatives: ECS, Lambda\n- Secrets alternatives: AWS Secrets Manager, Environment Variables\n- CI/CD alternatives: GitLab CI, Jenkins\n\n## Implementation Notes\n- Revisit when traffic or compliance requirements grow.\n',
    ),
    ArchitectureDecision(
        id='seed-enterprise-compliance',
        title='Enterprise compliance platform',
        status=ARCHITECTURE_DECISION_STATUS,
        summary='SOC2/HIPAA-oriented stack for a large team: ECS, Secrets Manager, and GitLab CI with balanced operational overhead.',
        createdAt='2026-01-12T14:30:00.000Z',
        content='# Architecture Decision Record\n\n## Status\nproposed\n\n## Context\n- Team size: 50+\n- Traffic pattern: variable\n- Budget sensitivity: performance-first\n- Compliance requirements: SOC2, HIPAA\n- Operational maturity: enterprise\n\n## Decision\n- **Compute:** ECS\n  - Alternatives: EKS, EC2\n- **Secrets:** AWS Secrets Manager\n  - Alternatives: HashiCorp Vault, AWS Parameter Store\n- **CI/CD:** GitLab CI\n  - Alternatives: GitHub Actions, AWS CodePipeline\n\n## Consequences\n- Stronger secrets controls and audit trails for regulated workloads.\n- Managed containers keep ops load lower than a full Kubernetes platform.\n\n## Alternatives Considered\n- Compute alternatives: EKS, EC2\n- Secrets alternatives: HashiCorp Vault, AWS Parameter Store\n- CI/CD alternatives: GitHub Actions, AWS CodePipeline\n\n## Implementation Notes\n- Validate controls against current cloud account standards before production.\n',
    ),
    ArchitectureDecision(
        id='seed-high-scale-eks',
        title='High-scale EKS delivery pipeline',
        status=ARCHITECTURE_DECISION_STATUS,
        summary='Spike-tolerant platform for a growing product: EKS, HashiCorp Vault, and AWS CodePipeline for high-spike traffic.',
        createdAt='2026-01-15T09:15:00.000Z',
        content='# Architecture Decision Record\n\n## Status\nproposed\n\n## Context\n- Team size: 21-50\n- Traffic pattern: high-spike\n- Budget sensitivity: balanced\n- Compliance requirements: SOC2\n- Operational maturity: advanced\n\n## Decision\n- **Compute:** EKS\n  - Alternatives: ECS, EC2\n- **Secrets:** HashiCorp Vault\n  - Alternatives: AWS Secrets Manager, AWS Parameter Store\n- **CI/CD:** AWS CodePipeline\n  - Alternatives: GitHub Actions, GitLab CI\n\n## Consequences\n- Kubernetes supports rapid horizontal scale during spikes.\n- Vault centralizes secrets for multi-account delivery.\n\n## Alternatives Considered\n- Compute alternatives: ECS, EC2\n- Secrets alternatives: AWS Secrets Manager, AWS Parameter Store\n- CI/CD alternatives: GitHub Actions, GitLab CI\n\n## Implementation Notes\n- Invest in platform tooling before peak launch windows.\n',
    ),
    ArchitectureDecision(
        id='seed-serverless-mvp',
        title='Serverless MVP for small teams',
        status=ARCHITECTURE_DECISION_STATUS,
        summary='Lambda-first MVP with Secrets Manager and GitHub Actions for a cost-sensitive team shipping quickly.',
        createdAt='2026-01-18T16:45:00.000Z',
        content='# Architecture Decision Record\n\n## Status\nproposed\n\n## Context\n- Team size: 1-5\n- Traffic pattern: variable\n- Budget sensitivity: cost-optimized\n- Compliance requirements: none\n- Operational maturity: moderate\n\n## Decision\n- **Compute:** Lambda\n  - Alternatives: ECS, EC2\n- **Secrets:** AWS Secrets Manager\n  - Alternatives: AWS Parameter Store, Environment Variables\n- **CI/CD:** GitHub Actions\n  - Alternatives: GitLab CI, Jenkins\n\n## Consequences\n- Minimal idle cost while validating product-market fit.\n- Cold starts and packaging limits may push a later move to containers.\n\n## Alternatives Considered\n- Compute alternatives: ECS, EC2\n- Secrets alternatives: AWS Parameter Store, Environment Variables\n- CI/CD alternatives: GitLab CI, Jenkins\n\n## Implementation Notes\n- Prefer Lambda when traffic is bursty and compute minutes stay low.\n',
    ),
    ArchitectureDecision(
        id='seed-multi-region-ecs',
        title='Multi-region ECS active-active',
        status=ARCHITECTURE_DECISION_STATUS,
        summary='Active-active ECS across regions with Secrets Manager and CodePipeline for unpredictable global traffic.',
        createdAt='2026-01-20T11:00:00.000Z',
        content='# Architecture Decision Record\n\n## Status\nproposed\n\n## Context\n- Team size: 21-50\n- Traffic pattern: unpredictable\n- Budget sensitivity: performance-first\n- Compliance requirements: SOC2\n- Operational maturity: advanced\n\n## Decision\n- **Compute:** ECS\n  - Alternatives: EKS, EC2\n- **Secrets:** AWS Secrets Manager\n  - Alternatives: HashiCorp Vault, AWS Parameter Store\n- **CI/CD:** AWS CodePipeline\n  - Alternatives: GitHub Actions, GitLab CI\n\n## Consequences\n- Regional isolation improves blast radius control.\n- Pipeline complexity rises with multi-account promotion paths.\n\n## Alternatives Considered\n- Compute alternatives: EKS, EC2\n- Secrets alternatives: HashiCorp Vault, AWS Parameter Store\n- CI/CD alternatives: GitHub Actions, GitLab CI\n\n## Implementation Notes\n- Define failover runbooks before enabling traffic shifting.\n',
    ),
    ArchitectureDecision(
        id='seed-fintech-vault',
        title='Fintech Vault hardening path',
        status=ARCHITECTURE_DECISION_STATUS,
        summary='PCI-oriented secrets posture with Vault, ECS, and GitLab CI for a mid-size payments team.',
        createdAt='2026-01-22T08:20:00.000Z',
        content='# Architecture Decision Record\n\n## Status\nproposed\n\n## Context\n- Team size: 6-20\n- Traffic pattern: variable\n- Budget sensitivity: balanced\n- Compliance requirements: PCI-DSS\n- Operational maturity: advanced\n\n## Decision\n- **Compute:** ECS\n  - Alternatives: EKS, Lambda\n- **Secrets:** HashiCorp Vault\n  - Alternatives: AWS Secrets Manager, AWS Parameter Store\n- **CI/CD:** GitLab CI\n  - Alternatives: GitHub Actions, Jenkins\n\n## Consequences\n- Centralized secrets rotation supports audit evidence.\n- Vault ops skill becomes a platform dependency.\n\n## Alternatives Considered\n- Compute alternatives: EKS, Lambda\n- Secrets alternatives: AWS Secrets Manager, AWS Parameter Store\n- CI/CD alternatives: GitHub Actions, Jenkins\n\n## Implementation Notes\n- Separate production Vault from developer namespaces early.\n',
    ),
    ArchitectureDecision(
        id='seed-ecommerce-spike-lambda',
        title='Ecommerce flash-sale Lambda',
        status=ARCHITECTURE_DECISION_STATUS,
        summary='Lambda + Parameter Store + GitHub Actions sized for high-spike flash sales on a lean ops budget.',
        createdAt='2026-01-24T13:40:00.000Z',
        content='# Architecture Decision Record\n\n## Status\nproposed\n\n## Context\n- Team size: 6-20\n- Traffic pattern: high-spike\n- Budget sensitivity: cost-optimized\n- Compliance requirements: none\n- Operational maturity: moderate\n\n## Decision\n- **Compute:** Lambda\n  - Alternatives: ECS, EC2\n- **Secrets:** AWS Parameter Store\n  - Alternatives: AWS Secrets Manager, Environment Variables\n- **CI/CD:** GitHub Actions\n  - Alternatives: GitLab CI, AWS CodePipeline\n\n## Consequences\n- Scales with campaign bursts without idle fleet cost.\n- Concurrency limits need explicit load testing.\n\n## Alternatives Considered\n- Compute alternatives: ECS, EC2\n- Secrets alternatives: AWS Secrets Manager, Environment Variables\n- CI/CD alternatives: GitLab CI, AWS CodePipeline\n\n## Implementation Notes\n- Reserve provisioned concurrency for checkout paths only.\n',
    ),
    ArchitectureDecision(
        id='seed-media-cdn-ec2',
        title='Media encoding on EC2',
        status=ARCHITECTURE_DECISION_STATUS,
        summary='Steady media encoding on EC2 with Secrets Manager and Jenkins for a content platform team.',
        createdAt='2026-01-26T09:05:00.000Z',
        content='# Architecture Decision Record\n\n## Status\nproposed\n\n## Context\n- Team size: 6-20\n- Traffic pattern: low-steady\n- Budget sensitivity: balanced\n- Compliance requirements: none\n- Operational maturity: moderate\n\n## Decision\n- **Compute:** EC2\n  - Alternatives: ECS, EKS\n- **Secrets:** AWS Secrets Manager\n  - Alternatives: AWS Parameter Store, HashiCorp Vault\n- **CI/CD:** Jenkins\n  - Alternatives: GitHub Actions, GitLab CI\n\n## Consequences\n- GPU/CPU shapes fit long-running encoding jobs.\n- Instance patching remains an operations burden.\n\n## Alternatives Considered\n- Compute alternatives: ECS, EKS\n- Secrets alternatives: AWS Parameter Store, HashiCorp Vault\n- CI/CD alternatives: GitHub Actions, GitLab CI\n\n## Implementation Notes\n- Auto-scale warm pools around known encoding windows.\n',
    ),
    ArchitectureDecision(
        id='seed-healthcare-hipaa-ecs',
        title='Healthcare HIPAA ECS baseline',
        status=ARCHITECTURE_DECISION_STATUS,
        summary='HIPAA-ready ECS with Secrets Manager and CodePipeline for clinical workflow services.',
        createdAt='2026-01-28T15:10:00.000Z',
        content='# Architecture Decision Record\n\n## Status\nproposed\n\n## Context\n- Team size: 21-50\n- Traffic pattern: variable\n- Budget sensitivity: performance-first\n- Compliance requirements: HIPAA\n- Operational maturity: enterprise\n\n## Decision\n- **Compute:** ECS\n  - Alternatives: EKS, EC2\n- **Secrets:** AWS Secrets Manager\n  - Alternatives: HashiCorp Vault, AWS Parameter Store\n- **CI/CD:** AWS CodePipeline\n  - Alternatives: GitLab CI, GitHub Actions\n\n## Consequences\n- Managed containers simplify BAA-covered operations.\n- Pipeline gates enforce change evidence for audits.\n\n## Alternatives Considered\n- Compute alternatives: EKS, EC2\n- Secrets alternatives: HashiCorp Vault, AWS Parameter Store\n- CI/CD alternatives: GitLab CI, GitHub Actions\n\n## Implementation Notes\n- Encrypt logs and backups in the same compliance boundary.\n',
    ),
    ArchitectureDecision(
        id='seed-data-platform-eks',
        title='Analytics data platform on EKS',
        status=ARCHITECTURE_DECISION_STATUS,
        summary='EKS + Vault + GitLab CI for a data platform team running unpredictable batch and serving workloads.',
        createdAt='2026-01-30T12:00:00.000Z',
        content='# Architecture Decision Record\n\n## Status\nproposed\n\n## Context\n- Team size: 21-50\n- Traffic pattern: unpredictable\n- Budget sensitivity: balanced\n- Compliance requirements: SOC2\n- Operational maturity: advanced\n\n## Decision\n- **Compute:** EKS\n  - Alternatives: ECS, EC2\n- **Secrets:** HashiCorp Vault\n  - Alternatives: AWS Secrets Manager, AWS Parameter Store\n- **CI/CD:** GitLab CI\n  - Alternatives: GitHub Actions, AWS CodePipeline\n\n## Consequences\n- Kubernetes scheduling fits mixed batch and online jobs.\n- Cluster upgrades need dedicated platform capacity.\n\n## Alternatives Considered\n- Compute alternatives: ECS, EC2\n- Secrets alternatives: AWS Secrets Manager, AWS Parameter Store\n- CI/CD alternatives: GitHub Actions, AWS CodePipeline\n\n## Implementation Notes\n- Isolate noisy neighbors with dedicated node groups.\n',
    ),
    ArchitectureDecision(
        id='seed-mobile-backend-serverless',
        title='Mobile BFF serverless backend',
        status=ARCHITECTURE_DECISION_STATUS,
        summary='Lambda BFF with Parameter Store and GitHub Actions for a small mobile product squad.',
        createdAt='2026-02-01T10:30:00.000Z',
        content='# Architecture Decision Record\n\n## Status\nproposed\n\n## Context\n- Team size: 1-5\n- Traffic pattern: variable\n- Budget sensitivity: cost-optimized\n- Compliance requirements: none\n- Operational maturity: minimal\n\n## Decision\n- **Compute:** Lambda\n  - Alternatives: ECS, EC2\n- **Secrets:** AWS Parameter Store\n  - Alternatives: AWS Secrets Manager, Environment Variables\n- **CI/CD:** GitHub Actions\n  - Alternatives: GitLab CI, Jenkins\n\n## Consequences\n- Low ops overhead for API aggregation.\n- Payload size and timeout limits constrain heavy media paths.\n\n## Alternatives Considered\n- Compute alternatives: ECS, EC2\n- Secrets alternatives: AWS Secrets Manager, Environment Variables\n- CI/CD alternatives: GitLab CI, Jenkins\n\n## Implementation Notes\n- Keep auth token exchange off the hot path where possible.\n',
    ),
    ArchitectureDecision(
        id='seed-saas-gitlab-delivery',
        title='SaaS multi-tenant GitLab delivery',
        status=ARCHITECTURE_DECISION_STATUS,
        summary='ECS multi-tenant SaaS with Secrets Manager and GitLab CI for balanced cost and release cadence.',
        createdAt='2026-02-03T14:00:00.000Z',
        content='# Architecture Decision Record\n\n## Status\nproposed\n\n## Context\n- Team size: 6-20\n- Traffic pattern: variable\n- Budget sensitivity: balanced\n- Compliance requirements: SOC2\n- Operational maturity: moderate\n\n## Decision\n- **Compute:** ECS\n  - Alternatives: EKS, Lambda\n- **Secrets:** AWS Secrets Manager\n  - Alternatives: HashiCorp Vault, AWS Parameter Store\n- **CI/CD:** GitLab CI\n  - Alternatives: GitHub Actions, AWS CodePipeline\n\n## Consequences\n- Tenant isolation maps cleanly to task definitions.\n- Shared clusters need careful quota and noisy-neighbor controls.\n\n## Alternatives Considered\n- Compute alternatives: EKS, Lambda\n- Secrets alternatives: HashiCorp Vault, AWS Parameter Store\n- CI/CD alternatives: GitHub Actions, AWS CodePipeline\n\n## Implementation Notes\n- Promote via environment-scoped protected variables.\n',
    ),
    ArchitectureDecision(
        id='seed-edge-iot-lambda',
        title='Edge IoT ingest with Lambda',
        status=ARCHITECTURE_DECISION_STATUS,
        summary='Event-driven Lambda ingest with Parameter Store and CodePipeline for unpredictable device traffic.',
        createdAt='2026-02-05T07:45:00.000Z',
        content='# Architecture Decision Record\n\n## Status\nproposed\n\n## Context\n- Team size: 6-20\n- Traffic pattern: unpredictable\n- Budget sensitivity: cost-optimized\n- Compliance requirements: none\n- Operational maturity: moderate\n\n## Decision\n- **Compute:** Lambda\n  - Alternatives: ECS, EC2\n- **Secrets:** AWS Parameter Store\n  - Alternatives: AWS Secrets Manager, Environment Variables\n- **CI/CD:** AWS CodePipeline\n  - Alternatives: GitHub Actions, GitLab CI\n\n## Consequences\n- Pay-per-invoke fits sparse device heartbeats.\n- Backpressure design is required for firmware update storms.\n\n## Alternatives Considered\n- Compute alternatives: ECS, EC2\n- Secrets alternatives: AWS Secrets Manager, Environment Variables\n- CI/CD alternatives: GitHub Actions, GitLab CI\n\n## Implementation Notes\n- Use DLQs and replay tooling before production device fleets.\n',
    ),
    ArchitectureDecision(
        id='seed-batch-analytics-ec2',
        title='Nightly batch analytics on EC2',
        status=ARCHITECTURE_DECISION_STATUS,
        summary='Scheduled EC2 batch with Parameter Store and Jenkins for low-steady overnight analytics.',
        createdAt='2026-02-07T18:20:00.000Z',
        content='# Architecture Decision Record\n\n## Status\nproposed\n\n## Context\n- Team size: 6-20\n- Traffic pattern: low-steady\n- Budget sensitivity: cost-optimized\n- Compliance requirements: none\n- Operational maturity: minimal\n\n## Decision\n- **Compute:** EC2\n  - Alternatives: ECS, Lambda\n- **Secrets:** AWS Parameter Store\n  - Alternatives: AWS Secrets Manager, Environment Variables\n- **CI/CD:** Jenkins\n  - Alternatives: GitHub Actions, GitLab CI\n\n## Consequences\n- Spot instances cut overnight compute spend.\n- Job orchestration stays simpler than a full cluster.\n\n## Alternatives Considered\n- Compute alternatives: ECS, Lambda\n- Secrets alternatives: AWS Secrets Manager, Environment Variables\n- CI/CD alternatives: GitHub Actions, GitLab CI\n\n## Implementation Notes\n- Shut down fleets automatically after batch completion windows.\n',
    ),
    ArchitectureDecision(
        id='seed-platform-codepipeline',
        title='Platform team CodePipeline golden path',
        status=ARCHITECTURE_DECISION_STATUS,
        summary='Enterprise golden-path delivery: ECS, Vault, and CodePipeline for a platform engineering org.',
        createdAt='2026-02-09T11:55:00.000Z',
        content='# Architecture Decision Record\n\n## Status\nproposed\n\n## Context\n- Team size: 50+\n- Traffic pattern: variable\n- Budget sensitivity: performance-first\n- Compliance requirements: SOC2, PCI-DSS\n- Operational maturity: enterprise\n\n## Decision\n- **Compute:** ECS\n  - Alternatives: EKS, EC2\n- **Secrets:** HashiCorp Vault\n  - Alternatives: AWS Secrets Manager, AWS Parameter Store\n- **CI/CD:** AWS CodePipeline\n  - Alternatives: GitLab CI, GitHub Actions\n\n## Consequences\n- Standardized pipelines reduce product-team delivery variance.\n- Central platform becomes a throughput bottleneck if understaffed.\n\n## Alternatives Considered\n- Compute alternatives: EKS, EC2\n- Secrets alternatives: AWS Secrets Manager, AWS Parameter Store\n- CI/CD alternatives: GitLab CI, GitHub Actions\n\n## Implementation Notes\n- Publish paved-road templates before mandating migration.\n',
    ),
    ArchitectureDecision(
        id='seed-internal-tools-github',
        title='Internal tools on GitHub Actions',
        status=ARCHITECTURE_DECISION_STATUS,
        summary='Internal tooling stack with ECS, Parameter Store, and GitHub Actions for a moderate maturity org.',
        createdAt='2026-02-11T09:30:00.000Z',
        content='# Architecture Decision Record\n\n## Status\nproposed\n\n## Context\n- Team size: 21-50\n- Traffic pattern: low-steady\n- Budget sensitivity: balanced\n- Compliance requirements: none\n- Operational maturity: moderate\n\n## Decision\n- **Compute:** ECS\n  - Alternatives: EC2, Lambda\n- **Secrets:** AWS Parameter Store\n  - Alternatives: AWS Secrets Manager, Environment Variables\n- **CI/CD:** GitHub Actions\n  - Alternatives: GitLab CI, Jenkins\n\n## Consequences\n- Developer familiarity speeds internal tool iteration.\n- OIDC to cloud roles removes long-lived CI credentials.\n\n## Alternatives Considered\n- Compute alternatives: EC2, Lambda\n- Secrets alternatives: AWS Secrets Manager, Environment Variables\n- CI/CD alternatives: GitLab CI, Jenkins\n\n## Implementation Notes\n- Separate internal tool accounts from customer-facing workloads.\n',
    ),
]
